---
- name: Validar servicio httpd
  hosts: web1, web2
  gather_facts: false

  tasks:
  - name: validar si httpd está instalado
    package:
      name:
        - httpd
      state: latest
    become: true
  - name: Copiar archivo httpd.conf
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/aranguiz82/ansible/main/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      mode: u=rw,g=r,o=r
    become: true
  - name: Enable service httpd
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
    become: true
  # - name: Reload service httpd, in all cases
  #   ansible.builtin.systemd_service:
  #     name: httpd.service
  #     state: reloaded
  #   become: true
  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      name: httpd
    become: true