---
- name: Validar servicio httpd
  hosts: web1, web2
  gather_facts: false

  tasks:
  - name: validar si httpd está instalado
    package:
      name:
        - httpd
      state: latest
    become: true
  - name: Enable service httpd and ensure it is not masked
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
      masked: no
    become: true
  - name: Copiar archivo httpd.conf
    ansible.builtin.get_url:
      url: https://github.com/aranguiz82/ansible/blob/20598523df1c4f55f3f307aaf23df7f041ee9f01/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      mode: u=rw,g=r,o=r
    become: true
  - name: Reload service httpd, in all cases
    ansible.builtin.systemd_service:
      name: httpd.service
      state: reloaded
    become: true
  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      name: httpd
    become: true